### ISSUE TITLE
Please add the IL cameras

### ISSUE THREAD

**Issue by blumzi** [tammojan/meteormap#1]
Hi Tammo, this is a wonderful tool!  Many thanks for making it!

Please add the Israeli cameras, as follows:

station_code: IL0001
    lon: 34.814694
    lat: 32.069778
    elev: 87.0

station_code: IL0002
    lon: 34.76222
    lat: 30.5975
    elev: 882.9

station_code: IL0003
    lon: 34.76222
    lat: 30.5975
    elev: 882.9

station_code: IL0004
    lon: 35.042631
    lat: 30.052243
    elev: 424.0

station_code: IL0006
    lon: 35.784863
    lat: 33.306667
    elev: 2020.0

station_code: IL0007
    lon: 35.0241461
    lat: 32.7772124
    elev: 191.1

**Comment by tammojan** [comment]
Thanks! I added them to the map (two digits of accuracy would've been enough).

**Comment by blumzi** [comment]
Hi Tammo,

I think *IL0003 *is missing from the meteor map.  It may be due to the fact
it is installed on the same mast as IL0002 (which
appears on the map).  *IL0003 *faces South while IL0002 faces North.

Please let me know if you need more information!

Many thanks,

- Arie

**Comment by tammojan** [comment]
Hi Arie, IL0003 is not currently part of the reduced data (which I inspect at gmn.uwo.ca/files/extracted_data), so probably best to check with Denis.

**Comment by blumzi** [comment]
Hey Tammo,

I took it up with the boss.  It really was left out due to some ancient
reasoning.  It's back again, so I expect it to magically show up.

Thanks for pointing me in the right direction,

- Arie
