### ISSUE TITLE
FOV layer

### ISSUE THREAD

**Issue by meteorkees** [tammojan/meteormap#6]
A layer which shows the FOV could be be useful to figure out which part of the sky the stations looking ad. I.g. if a new stations set up, with a whimp you can see what will be a good direction and/ore elevation.

And I noticed that to find meteors in a specific direction, the fov of the stations is handy to compare visual captured meteors and radio reflection meteors. 
+Denis wanted to have a FOV map build on the KML files already, so; "2 vliegen in een klap"  :-)

**Comment by tammojan** [comment]
Thanks, I'll look into this.

**Comment by tammojan** [comment]
This has been implemented now.
